[[main]]
  name = "Engineering"
  pageRef = "engineering"
  weight = 10

[[main]]
  name = "Topics"
  pageRef = "topics"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Search"
  pageRef = "search"
  weight = 40

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/yxiaoli"
  weight = 50
